# Завдання 1
Виріши аналітично задачу з текстовою умовою

Над проектом працювало 3 типи спеціалістів - дизайнери, розробники та тестувальники. Ми знаємо кількість годин на кожному етапі розробки та кількість грошей, які закладені на виконання кожного етапу в якості собівартості.
Всю розробку менеджер розділив на 3 етапи: створення дизайну, розробка програмної частини, фінальне тестування.

На першому етапі відпрацьовано 20 годин дизайнером та 3 години розробниками - на даному етапі до смети закладено 775 доларів.
На другому етапі дизайнери відпрацювали 8 годин, розробники - 28, а тестувальники - 4. Даний етап було оцінено в 1012 доларів.
На фінальному етапі дизайнери відпрацювали 4 години, розробники - 12, а тестувальники 32. Трудові ресурси на цьому етапі оцінені в 696 доларів.

Знайди вартість години у кожного спеціаліста шляхом вирішення системи лінійних рівнянь, базуючись на даних по етапах розробки.

Розв'язок:

$$
\overline x =
\left (\begin{array}{cc}
x - вартість\:години\:роботи\:дизайнера\\
y - вартість\:години\:роботи\:розробника\\
z - вартість\:години\:роботи\:тестувальника
\end{array}\right)
\left\{\begin{matrix}
20x+3y=775(перший\:етап)\\
8x+28y+4z=1012(другий\:етап)\\
4x+12y+32z=696 (третій\:етап)
\end{matrix}\right.
\\
A =
\left (\begin{array}{cc}
20 & 3 & 0 \\
8 & 28 & 4 \\
4 & 12 & 32
\end{array}\right)
\\
b =
\left (\begin{array}{cc}
775 \\
1012 \\
696
\end{array}\right)
\\
A \overline x = b
$$

*Розв'язувати можна будь-яким методом, але метод Крамера, потенційно, буде найлегшим*

###По-перше, треба знайти визначник матриці і перевірити чи він є ненульовим,тоді система рівнянь матиме один розв'язок.
$$
\Delta = \left|A\right|=
\begin{vmatrix}
20 & 3 & 0\\
8 & 28 & 4\\
4 & 12 & 32
\end{vmatrix}\
$$
\
$$
\Delta=
20(28⋅32−4⋅12)−3(8⋅32−4⋅4)+0(8⋅12−28⋅4)=20(896−48)−3(256−16)+0(96−112)=20⋅848−3⋅240+0⋅(−16)\\
$$
$$
\Delta=16960−720=16240
$$

In [2]:
# Його можна обчислити за допомогою Python
import numpy as np

# запис даних у матричну форму А
A = np.array([
    [20, 3, 0],
    [8, 28, 4],
    [4, 12, 32]
])

# трудові ресурси на кожному етапі можна ввести у вигляді вектора b
b = np.array([775, 1012, 696])

# і вичислити визначник матриці A
det_A = np.linalg.det(A)

# визначник матриці A є ненульовим
print(det_A)

16240.000000000005


####далі треба обчислити визначники $\Delta_{x}$\,$\Delta_{y}$\, $\Delta_{z}$ шляхом заміни відповідних стовпців на вектор b.


#Обчислення $\Delta_{x}$
$$
A_{x}=
\begin{vmatrix}
775 & 3 & 0\\
1012 & 28 & 4\\
696 & 12 & 32
\end{vmatrix}\
$$
\
$$
\Delta_{x}=
775\begin{vmatrix}
 28 & 4\\
 12 & 32
\end{vmatrix}-3\begin{vmatrix}
 1012 & 4\\
 696 & 32
\end{vmatrix}+0\begin{vmatrix}
 1012 & 28\\
 696 & 12
\end{vmatrix}=775((28⋅32)−(4⋅12))-3((1012⋅32)−(4⋅696))+0=\\
=775(896−48)−3(32384−2784)\\
$$
$$
\Delta_{x}=656200−88800=567400
$$


#Обчислення $\Delta_{y}$
$$
A_{y}=
\begin{vmatrix}
20 & 775 & 0\\
8 & 1012 & 4\\
4 & 696 & 32
\end{vmatrix}\
$$
\
$$
\Delta_{y}=
20\begin{vmatrix}
 1012 & 4\\
 696 & 32
\end{vmatrix}-775\begin{vmatrix}
 8 & 4\\
 4 & 32
\end{vmatrix}+0\begin{vmatrix}
 8 & 1012\\
 4 & 696
\end{vmatrix}=20⋅29600-775((8⋅32)−(4⋅4))+0\\
$$
$$
\Delta_{y}=592000−186000=406000
$$


#Обчислення $\Delta_{z}$
$$
A_{z}=
\begin{vmatrix}
20 & 3 & 775\\
8 & 28 & 1012\\
4 & 12 & 696
\end{vmatrix}\
$$
\
$$
\Delta_{z}=
20\begin{vmatrix}
 28 & 1012\\
 12 & 696
\end{vmatrix}-3\begin{vmatrix}
 8 & 1012\\
 4 & 696
\end{vmatrix}+775\begin{vmatrix}
 8 & 28\\
 4 & 12
\end{vmatrix}=20((28⋅696)−(1012⋅12))-3((8⋅696)−(1012⋅4))+775((8⋅12)−(28⋅4))=\\
=20(19488−12144)-3(5568−4048)+775(96−112)\\
$$
$$
\Delta_{z}=146880−4560−12400=129920
$$

In [3]:
import numpy as np
# можна провести обчислення за допомогою Python
# заміна відповідних стовбців у матрицях A_x, A_y, A_z
A_x = np.copy(A)
A_x[:, 0] = b

A_y = np.copy(A)
A_y[:, 1] = b

A_z = np.copy(A)
A_z[:, 2] = b

# вичислення детермінантів
det_A_x = np.linalg.det(A_x)
det_A_y = np.linalg.det(A_y)
det_A_z = np.linalg.det(A_z)

print(det_A_x)
print(det_A_y)
print(det_A_z)

568399.9999999998
405999.99999999953
129920.00000000007


##тепер можна обчислити вартість години роботи кожного спеціаліста
$$
x(дизайнера)=
\frac{\Delta_{x}}{\Delta}
=
\frac{568 400}{16 240}=35\:доларів
$$
\
$$
y(розробника)=
\frac{\Delta_{y}}{\Delta}
=
\frac{406 000}{16 240}=25\:доларів
$$
\
$$
z(тестувальника)=
\frac{\Delta_{z}}{\Delta}
=
\frac{129 920}{16 240}=8\:доларів
$$

Перевірка: $x+y+z = 68$

# Завдання 2
- Задай матрицю та вектор вільних членів для наступної системи:

$$
\left\{\begin{matrix}
-x_1+х_2+2x_3=1\\
-x_2-3x_3=-4\\
4x_1-3x_2+2x_3=7
\end{matrix}\right.
$$
##Виразимо матрицю A та вектор b:
$$
A =
\left (\begin{array}{cc}
-1 & 1 & 2 \\
0 & -1 & -3 \\
4 & -3 & 2
\end{array}\right)
$$
$$
b =
\left (\begin{array}{cc}
1 \\
-4 \\
7
\end{array}\right)
$$


In [4]:
import numpy as np
A = np.array([
    [-1, 1, 2],
    [0, -1, -3],
    [4, -3, 2]
]
)
B = np.array([1, -4, 7])

# Розв'язання системи лінійних рівнянь за допомогою метода солве
x = np.linalg.solve(A, b)

# Виводимо розв'язок
print(x)

[-2473.85714286 -3072.57142857   686.85714286]



- Напиши функцію для вирішення системи матричним методом
- Напиши функцію для вирішення системи методом Крамера

In [5]:
# Напиши функцію для вирішення системи матричним методом
def solve_inv_matrix(a, b, verbose=False):
    """
    Розв'язує систему лінійних рівнянь за допомогою оберненої матриці.

    Параметри:
    a (numpy.ndarray): Матриця коефіцієнтів.
    b (numpy.ndarray): Вектор вільних членів.
    verbose (bool): Якщо True, виводить проміжні кроки.

    Повертає:
    numpy.ndarray: Вектор розв'язків.
    """
    # Обчислюємо обернену матрицю
    a_inv = np.linalg.inv(a)

    if verbose:
        print("Обернена матриця A:\n", a_inv)

    # Розв'язуємо систему рівнянь
    x = np.dot(a_inv, b)

    if verbose:
        print("Вектор розв'язків x:\n", x)

    return x

# матриця коефіцієнтів A
A = np.array([
    [-1, 1, 2],
    [0, -1, -3],
    [4, -3, 2]
])

# вводимо вектор вільних членів b
B = np.array([1, -4, 7])

# Викликає функцію для розв'язання системи
print(f"Вектор рішення: \r\n {solve_inv_matrix(A, B)}")


Вектор рішення: 
 [2. 1. 1.]


In [6]:
# Напиши функцію для вирішення системи методом Крамера

def solve_cramer(a, b, verbose=False):
    """
    Розв'язує систему лінійних рівнянь методом Крамера.

    Параметри:
    a (numpy.ndarray): Матриця коефіцієнтів.
    b (numpy.ndarray): Вектор вільних членів.
    verbose (bool): Якщо True, виводить проміжні кроки.

    Повертає:
    numpy.ndarray: Вектор розв'язків.
    """
    n = a.shape[0]
    det_a = np.linalg.det(a)

    if verbose:
        print("Визначник матриці A:", det_a)

    if det_a == 0:
        raise ValueError("Матриця коефіцієнтів є виродженою (визначник дорівнює нулю), система не має єдиного розв'язку.")

    x = np.zeros(n)

    for i in range(n):
        a_i = np.copy(a)
        a_i[:, i] = b
        det_a_i = np.linalg.det(a_i)

        if verbose:
            print(f"Визначник матриці A з заміненим стовпцем {i}:", det_a_i)

        x[i] = det_a_i / det_a

    return x

# Задається матриця коефіцієнтів A
A = np.array([
    [-1, 1, 2],
    [0, -1, -3],
    [4, -3, 2]
])

# Задається вектор вільних членів b
B = np.array([1, -4, 7])

# Викликається функція для розв'язання системи
print(f"Вектор рішення: \r\n {solve_cramer(A, B)}")

Вектор рішення: 
 [2. 1. 1.]
