In [ ]:
#Встaновити numpy
#!pip install numpy

In [5]:
# Приклади роботи з матрицями
import numpy as np

# Задаємо матрицю 3*3
m_sqr_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матриця:")
print(m_sqr_arr)

# Ще один варіант задати матрицю
m_sqr_mx = np.matrix([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матриця (ще один варіант):")
print(m_sqr_mx)

Матриця:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Матриця (ще один варіант):
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [10]:
# Побудуємо діагональ
diag = np.diag(m_sqr_mx)
print("Діагональ:")
print(diag)

# Побудуємо діагональну матрицю на основі діагоналі
m_diag_np = np.diag(np.diag(m_sqr_mx))
print("Діагональна матриця:")
print(m_diag_np)



Діагональ:
[1 5 9]
Діагональна матриця:
[[1 0 0]
 [0 5 0]
 [0 0 9]]


In [8]:
# Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.
matrix = np.zeros((3, 3), dtype=int)
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [9]:
# Створіть масив розміром 4x4, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.
matrix = np.random.randint(11, size=(4,4))
print(matrix)

[[ 6  9  0  0]
 [ 3  6  0  2]
 [ 0  1 10  6]
 [ 8  2  6  5]]


In [18]:
#матриця з одиниць
matrix = np.ones((3, 3), dtype=int)
print(matrix)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [20]:
# Транспонована матриця
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Матриця a:")
print(a)
a_t = a.transpose()
print("Транспонована матриця:")
print(a_t)
print("Ще один спосіб транспонування матриці:")
print(a.T)

# Визначник матриці
a = np.array([[1, 2], [3, 4]])
a_det = np.linalg.det(a)
print("Визначник матриці:")
print(a_det.round(2))



Матриця a:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Транспонована матриця:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Ще один спосіб транспонування матриці:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Визначник матриці:
-2.0


In [21]:
# Множення матриці на число 
a = np.matrix([[1, 2, 3], [4, 5, 6]])
c = 3 * a
print("Множення матриці на число:")
print(c)


Множення матриці на число:
[[ 3  6  9]
 [12 15 18]]


In [22]:
# Додавання матриць
a = np.matrix([[1, 6, 3], [8, 2, 7]])
b = np.matrix([[8, 1, 5], [6, 9, 12]])
c = a + b
print("Додавання матриць:")
print(c)



Додавання матриць:
[[ 9  7  8]
 [14 11 19]]


In [23]:
# Добуток матриць
a = np.matrix([[1, 2, 3], [4, 5, 6]])
b = np.matrix([[7, 8], [9, 1], [2, 3]])
c = np.dot(a, b)
print("Добуток матриць:")
print(c)



Добуток матриць:
[[31 19]
 [85 55]]


In [24]:
# Обернена матриця
a = np.matrix([[1, -3], [2, 5]])
a_inv = np.linalg.inv(a)
print("Обернена матриця:")
print(a_inv)


Обернена матриця:
[[ 0.45454545  0.27272727]
 [-0.18181818  0.09090909]]


In [25]:
# Ранг матриці
rank = np.linalg.matrix_rank(a)
print("Ранг матриці:")
print(rank)

Ранг матриці:
2


In [1]:
a = np.array([[1, 6, 3], [8, 2, 7]])
b = np.array([[8, 1, 5], [6, 9, 12]])

c1 = a*b
print("Поелементний добуток матриць:")
print(c1)

NameError: name 'np' is not defined