#Матриці та операції над ними

# Практика
## Розмірність матриці:
**Завдання**

Знайдіть розмірність у матриць:

$A=\begin{pmatrix}
2 & 0 & 0 & 1 \\
0 & −1 & 2 & 1 \\
2 & 1 & 0  & 3
\end{pmatrix}$.  

$B=\begin{pmatrix}
2 & 0  \\
0 & −1 \\
2 & 1
\end{pmatrix}$.


$C=\begin{pmatrix}
2 & 0 & 0 & 1 \\
0 & −1 & 2 & 1 \\
0 & −1 & 2 & 1  \\
2 & 1 & 0  & 3 \\
2 & 0 & 0 & 1
\end{pmatrix}$.

**Додаткове завдання:**
1. Напишіть програму, яка генерує матрицю заданої розмірності та заповнює її випадковими цілими числами.
2. Напишіть програму, яка генерує одиничну матрицю випадкової розмірності.
3. Напишіть програму, яка генерує матрицю заданої розмірності із заповненою лише зворотньою діагоналлю.


Визначення розмірності матриці засобами Numpy

In [2]:
import numpy as np

def get_matrix_dimensions(matrix):

    
    """
    Функція повертає розмірність матриці (кількість строк та стовпців).

    Параметри:
    - matrix: numpy.ndarray, вхідна матриця.

    Повертає:
    - tuple: Кортеж із кількістю строк та стовпців матриці.
    """
    num_rows, num_columns = matrix.shape
    return num_rows, num_columns

# Приклад використання
example_matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
dimensions = get_matrix_dimensions(example_matrix)

print("Кількість строк:", dimensions[0])
print("Кількість стовпців:", dimensions[1])


Кількість строк: 3
Кількість стовпців: 3


Генерування випадкової матриці

In [ ]:
def generate_random_matrix(rows, columns, low_limit, high_limit):
    """
    Функція генерує матрицю заданої розмірності та заповнює її випадковими числами з вказаним інтервалом.

    Параметри:
    - rows: int, кількість строк матриці.
    - columns: int, кількість стовпців матриці.
    - low_limit: int, нижня межа інтервалу для випадкових чисел.
    - high_limit: int, верхня межа інтервалу для випадкових чисел.

    Повертає:
    - numpy.ndarray: Випадково заповнена матриця.
    """
    random_matrix = np.random.randint(low_limit, high_limit, size=(rows, columns))
    return random_matrix

# Параметри матриці
rows = 3
columns = 4
low_limit = 1
high_limit = 10

# Генеруємо та виводимо матрицю
random_matrix = generate_random_matrix(rows, columns, low_limit, high_limit)
print("Випадково заповнена матриця:")
print(random_matrix)


Випадково заповнена матриця:
[[3 2 1 5]
 [6 1 1 8]
 [2 8 3 5]]


Генерування одиничної матриці випадкової розмірності

In [ ]:
import random
def gen_eye_matrix(row):
    return np.eye(row)



n = random.randint(1, 100)  # Генерує випадкове число в діапазоні від 1 до 100

eye_matrix = gen_eye_matrix(n)

print("Одинична матриця:")
print(eye_matrix)

get_matrix_dimensions(eye_matrix)

Одинична матриця:
[[1. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


(94, 94)

Генерування матриці заданої розмірності із заповненою лише зворотньою діагоналлю

In [ ]:
import numpy as np
import random

def generate_reverse_diagonal_matrix(size):
    """
    Функція генерує квадратну матрицю заданої розмірності із заповненою лише зворотньою діагоналлю випадковими даними.

    Параметри:
    - size: int, розмірність квадратної матриці.

    Повертає:
    - numpy.ndarray: Матриця із заповненою лише зворотньою діагоналлю випадковими даними.
    """
    matrix = np.zeros((size, size), dtype=int)

    # Генеруємо випадкові числа та заповнюємо зворотню діагональ
    for i in range(size):
        matrix[size - i - 1, i] = random.randint(1, 10)

    return matrix

# Задаємо розмірність матриці
matrix_size = 5

# Генеруємо та виводимо матрицю із заповненою лише зворотньою діагоналлю випадковими даними
result_matrix = generate_reverse_diagonal_matrix(matrix_size)
print("Матриця із заповненою лише зворотньою діагоналлю випадковими даними:")
print(result_matrix)


Матриця із заповненою лише зворотньою діагоналлю випадковими даними:
[[0 0 0 0 5]
 [0 0 0 6 0]
 [0 0 2 0 0]
 [0 3 0 0 0]
 [2 0 0 0 0]]


## Операції із матрицями
**Завдання**

1. $\begin{pmatrix}
1 & 2 \\
 0 & 1\end{pmatrix} + \begin{pmatrix}
1 & 2 \\
 0 & 1\end{pmatrix}$  


 2. Якщо $A = \begin{pmatrix}
 1 & 3 &−1 \\
0 & 1 & −1 \\
1 & 1 & 2
\end{pmatrix} , B= \begin{pmatrix}
1 & −3 & 2\\
−1 & 0 & 1 \\
2 & 1 & 1 \end{pmatrix}$, обрахуйте:  
$
a. 2A− 3B;   $  
$b. A+ 5B;  $  
$c. −A− 2B; $   
$d. 7A−B;  $  
$e. 3A−B;  $  
$f. 2A+ 2B;  $  
$g. A− 2B;  $  
$h. 4A+B;  $  
$i. 2A− 4B;  $  
$j. 7A− 2B;  $  

**Додаткове завдання:**
1. Напишіть програму, яка отримує значення матриць (париклад, з CSV файла) та робить із матрицями обрахунки за запитом від користувача


In [ ]:
import numpy as np
import pandas as pd

# Припустимо, у нас є матриця
matrixA = np.array([[1, 3, -1], [0, 1, -1], [1, 1, 2]])
matrixB = np.array([[1, -3, 2], [-1, 0, 1], [2, 1, 1]])
# Створення DataFrame з матриці
dfA = pd.DataFrame(matrixA)
dfB = pd.DataFrame(matrixB)

# Запис у CSV файл
dfA.to_csv('matrixA.csv', index=False, header=False)
dfB.to_csv('matrixB.csv', index=False, header=False)

In [ ]:
def matrix_mul(A, B):
    # Перевіряємо умову добутку
    if A.shape[1] != B.shape[0]:
        raise ValueError("Неможливо помножити ці матриці. Кількість стовпців у A "
                         "повинна дорівнювати кількості рядків у B.")

    # Помножимо матриці
    res = np.dot(A, B)
    return res


In [ ]:
def matrix_add(A, B):
    # Перевіряємо, чи матриці мають однаковий розмір
    if A.shape != B.shape:
        raise ValueError("Матриці мають різні розміри, додавання неможливе.")

    # Додаємо матриці
    res = A + B
    return res

In [ ]:
import pandas as pd
def get_matrix_eval(file_path1, file_path2):
    matrix1 = pd.read_csv(file_path1, header=None).values
    matrix2 = pd.read_csv(file_path2, header=None).values

    operation = input("Виберіть операцію (додавання, добуток, добуток_число): ")

    if operation == 'додавання':
        result = matrix_add(matrix1, matrix2)
    elif operation == 'добуток':
        result = matrix_mul(matrix1, matrix2)
    elif operation == 'добуток_число':
        coef = float(input("Введіть число для множення: "))
        result = coef * matrix1
    else:
        result = None
        print("Неправильна операція!")

    return result

# Приклад використання:
res = get_matrix_eval('matrixA.csv', 'matrixB.csv')

if res is not None:
    print("Результат:")
    print(res)

Виберіть операцію (додавання, добуток, добуток_число): добуток_число
Введіть число для множення: 2
Результат:
[[ 2.  6. -2.]
 [ 0.  2. -2.]
 [ 2.  2.  4.]]


## Добуток матриць
$A = \begin{pmatrix}
−2& −3 &1 \\
0 &1& 4\\
2& −2& 0\end{pmatrix}$.  

$B = \begin{pmatrix}
−2 &6& −2\\
7 &0& 3\\
−1& 3& 9\end{pmatrix}$.  

$C = \begin{pmatrix}
0 &3& −2\\
0 &3 &1\\
3 &4 &−3\\
\end{pmatrix}$.  


$D = \begin{pmatrix}
2 &−3& 1\\
−5& 3& 2\\
2& 0& 7 \end{pmatrix}$.  

**Завдання**

Виконайте обрахунки: $AB, CD, AC, BD$

**Додаткове завдання:**
1. Напишіть програму, яка генерує приклади на тренування обрахування добутку матриць.
2. Допрацюйте програму так, щоб вона приймала рішення, їх перевіряла та фіксувала швидкість виконання людиною операції із множення матриць.

1

In [ ]:
import numpy as np

def generate_matrix_multiplication_examples(num_examples, matrix_size):
    examples = []

    for _ in range(num_examples):
        matrix1 = np.random.randint(1, 10, size=(matrix_size, matrix_size))
        matrix2 = np.random.randint(1, 10, size=(matrix_size, matrix_size))
        product = np.dot(matrix1, matrix2)
        examples.append((matrix1, matrix2, product))

    return examples

# Example usage:
examples = generate_matrix_multiplication_examples(5, 3)
for i, (matrix1, matrix2, product) in enumerate(examples, 1):
    print(f"Example #{i}:")
    print(f"Matrix 1:\n{matrix1}")
    print(f"Matrix 2:\n{matrix2}")
    print(f"Expected product:\n{product}\n")


Example #1:
Matrix 1:
[[3 8 5]
 [3 3 9]
 [7 9 8]]
Matrix 2:
[[2 7 8]
 [7 9 5]
 [1 9 5]]
Expected product:
[[ 67 138  89]
 [ 36 129  84]
 [ 85 202 141]]

Example #2:
Matrix 1:
[[8 4 7]
 [8 9 5]
 [9 4 6]]
Matrix 2:
[[8 4 4]
 [7 4 4]
 [2 3 4]]
Expected product:
[[106  69  76]
 [137  83  88]
 [112  70  76]]

Example #3:
Matrix 1:
[[7 1 3]
 [3 9 3]
 [7 6 1]]
Matrix 2:
[[2 7 9]
 [7 9 5]
 [3 3 9]]
Expected product:
[[ 30  67  95]
 [ 78 111  99]
 [ 59 106 102]]

Example #4:
Matrix 1:
[[4 5 5]
 [5 7 5]
 [5 8 6]]
Matrix 2:
[[2 8 8]
 [3 1 5]
 [5 4 4]]
Expected product:
[[ 48  57  77]
 [ 56  67  95]
 [ 64  72 104]]

Example #5:
Matrix 1:
[[8 2 7]
 [9 2 1]
 [6 5 9]]
Matrix 2:
[[2 4 3]
 [9 4 7]
 [8 8 8]]
Expected product:
[[ 90  96  94]
 [ 44  52  49]
 [129 116 125]]



2

In [ ]:
import numpy as np
import time

def generate_matrix_multiplication_example(matrix_size):
    matrix1 = np.random.randint(1, 10, size=(matrix_size, matrix_size))
    matrix2 = np.random.randint(1, 10, size=(matrix_size, matrix_size))
    product = np.dot(matrix1, matrix2)

    # Display the matrices and prompt the user to solve
    print(f"Solve the matrix multiplication:\n")
    print(f"Matrix 1:\n{matrix1}\n")
    print(f"Matrix 2:\n{matrix2}\n")

    # Record the start time
    start_time = time.time()

    # Prompt user for the solution
    user_solution = input(f"Enter your solution for the product matrix (comma-separated row values): ")
    user_solution = np.array(list(map(int, user_solution.split(',')))).reshape(matrix_size, matrix_size)

    # Record the end time
    end_time = time.time()

    # Check if the user's solution is correct
    if np.array_equal(user_solution, product):
        print(f"\nCorrect! It took you {end_time - start_time:.2f} seconds.")
    else:
        print(f"\nIncorrect. The correct product matrix is:\n{product}")

# Example usage:
generate_matrix_multiplication_example(3)


Solve the matrix multiplication:

Matrix 1:
[[8 2 4]
 [7 4 3]
 [7 8 5]]

Matrix 2:
[[2 8 4]
 [3 1 1]
 [9 1 1]]

Enter your solution for the product matrix (comma-separated row values): 58, 70, 38, 53, 63, 35, 83, 69, 41

Correct! It took you 154.94 seconds.
